# Configuration for Alacritty, the GPU enhanced terminal emulator.
#
import:
  - ~/.alacritty-colorscheme/themes/darcula.yaml
font:
  normal:
    family: UbuntuMono Nerd Font
    style: Regular
  bold:
    family: UbuntuMono Nerd Font
    style: Bold
  italic:
    family: UbuntuMono Nerd Font
    style: Italic
  bold_italic:
    family: UbuntuMono Nerd Font
    style: Bold Italic
  size: 15
